version: '3.4'

services:
  application:
    build:
      context: '.'
      dockerfile: './Dockerfile'
    container_name: application
    restart: always
    ports:
      - 5000:5000
    networks:
      - metrics

networks:
  metrics:
    driver: bridge